### ISSUE TITLE
Need some way to supply path of real `cpp`

### ISSUE THREAD

**Issue by jryans** [stephenrkell/toolsub#2]
`guessCppCommandAndLang` tries to find the "real" `cpp` command, but on macOS, it's unlikely that the GNU `cpp` program with the default one on the user's `PATH` (and the Clang-backed `cpp` command that is there seems to fail in some way I don't quite understand yet).

https://github.com/stephenrkell/toolsub/blob/65e4631f5b55b842ffe12171ab061b0af19d6d3d/wrapper/src/compiler_args.ml#L72

To workaround this, we could check some optional environment variable that can supply the real `cpp` path... but the obvious variable name `CPP` is already occupied by the wrap-using tooling (e.g. `dbgcov`), so maybe it would need to be `REAL_CPP`...?

**Comment by stephenrkell** [comment]
That's 65e4631 I should say.

**Comment by jryans** [comment]
Ah thanks, that's seems to work. I'll adapt that same approach for `dbgcov`. 😄
